version: "3.9"

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GATEWAY_AUTH_BASE_URL=http://cinema-auth-service:8081
      - GATEWAY_SERVICES_AUTH=http://cinema-auth-service:8081
      - GATEWAY_SERVICES_USERS=http://cinema-users-service:8082
      - GATEWAY_SERVICES_MOVIES=http://cinema-movies-service:8083
      - GATEWAY_SERVICES_CINEMAS=http://cinema-cinemas-service:8084
      - GATEWAY_SERVICES_TICKETS=http://13.59.250.112:8085
      - GATEWAY_SERVICES_ADS=http://18.221.146.156:8086
      - GATEWAY_SERVICES_REPORTS=http://3.143.243.97:8087
    depends_on:
      - cinema-auth-service
      - cinema-users-service
      - cinema-movies-service
      - cinema-cinemas-service
    networks:
      - cinema-net

  cinema-auth-service:
    image: auth-service:latest
    container_name: cinema-auth-service
    ports:
      - "8081:8081"
    networks:
      - cinema-net

  cinema-users-service:
    image: users-service:latest
    container_name: cinema-users-service
    ports:
      - "8082:8082"
    networks:
      - cinema-net

  cinema-movies-service:
    image: movies-service:latest
    container_name: cinema-movies-service
    ports:
      - "8083:8083"
    networks:
      - cinema-net

  cinema-cinemas-service:
    image: cinemas-service:latest
    container_name: cinema-cinemas-service
    ports:
      - "8084:8084"
    networks:
      - cinema-net

networks:
  cinema-net:
    driver: bridge
