server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  http:
    codecs:
      max-in-memory-size: 4MB
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    gateway:
      access: unrestricted

gateway:
  auth-service:
    base-url: ${GATEWAY_AUTH_BASE_URL:${GATEWAY_SERVICES_AUTH:http://cinema-auth-service:8081}}
  services:
    auth: ${GATEWAY_SERVICES_AUTH:http://cinema-auth-service:8081}
    users: ${GATEWAY_SERVICES_USERS:http://cinema-users-service:8082}
    movies: ${GATEWAY_SERVICES_MOVIES:http://cinema-movies-service:8083}
    cinemas: ${GATEWAY_SERVICES_CINEMAS:http://cinema-cinemas-service:8084}
    tickets: ${GATEWAY_SERVICES_TICKETS:http://13.59.250.112:8085}
    ads: ${GATEWAY_SERVICES_ADS:http://18.221.146.156:8086}
    reports: ${GATEWAY_SERVICES_REPORTS:http://3.143.243.97:8087}
  rate-limit:
    replenish-rate: 15
    burst-capacity: 30
    requested-tokens: 1
